### PR TITLE
Geojson support add output

### PR DESCRIPTION
**Pull request by AndGem**

### CODE REVIEW

**Comment by morandd** [comment]
Could you support generating both .poly and .geojson outputs in the same run (ie. so we don't have to run the program twice to get both formats)?
(Apologies if you've already thought of this...)

**Comment by AndGem** [comment]
Hey @morandd ,

yes, this is already included. I probably will need your help though, because I'm not sure if my output is correct. I've never worked with GeoJSON before.

I'll post something in the issue once the PR is in a state where I can produce proper output.

**Comment by morandd** [comment]
The GeoJSON output is unfortunately not valid GeoJSON. Currently it outputs only "coordinates" but it needs to output the type and properties fields as well in order to be parsable GeoJSON. The spec is here: [https://geojson.org]. Crucially, it needs to identify the output as a Polygon or MultiPolygon and wrap that inside a Feature.  This is easy to do, just needs a bit of wrapper text around your current output. Something like this:

```
currentOutput = '"coordinates": .... // What the tool currently generates as output
correctOutput = "";
geomType = multi ? 'MultiPolygon' : 'Polygon'; // Set this based on the current geometry
correctOutput = '{ "type": "Feature", "geometry": { "type": "' + geomType + '",
    "coordinates": [125.6, 10.1]'. + currentOutput  + 
' }, "properties": {   "name": "Dinagat Islands" }}'; // Potentially include all Properties from the OSM relation here too? That would be rather useful I think.
```

**Comment by AndGem** [comment]
Hi @morandd ,

as always. Thanks for the feedback. I've created just now version `v.0.3.1`. Can you take a look when you have time?

**Pull request merged**
